apiVersion: v1
kind: PersistentVolume
metadata:
  name: drogon-app-pv
  namespace: drogon-project
spec:
  capacity:
    storage: "1Gi"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /app/db/data