apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drogon-app-pvc
  namespace: drogon-project
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce